# [colors.primary]
# background = "#fdf6e3"
# foreground = "#657b83"

import = [
    "~/.config/alacritty/themes/themes/_active.toml"
]

[window]
dynamic_title = true

[window.padding]
x = 2
y = 2

[env]
# TERM = "xterm-256color"

[font]
size = 9.5
