swipe:
  3:
    up:
      command: "wtype 'Three finger swipe up'"
    down:
      command: "wtype 'Three finger swipe down'"
    left:
      command: "hyprctl dispatch workspace e-1"
    right:
      command: "hyprctl dispatch workspace e+1"

pinch:
  in:
    command: "wtype 'Pinch in'"
  out:
    command: "wtype 'Pinch out'"

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
