[device]
input = "/dev/input/by-path/platform-i8042-serio-0-event-kbd"
output = "uinput"

[keymap]
base = [
  ["esc", "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12"],
  ["`", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "backspace"],
  ["tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "[", "]", "\\"],
  ["caps", "a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "'", "enter"],
  ["lshift", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/", "rshift"],
  ["lctrl", "lalt", "lmeta", "space", "ralt", "rmeta", "left", "down", "up", "right"]
]

[layers]
kodamaq = [
  [{tap = "esc", hold = "lctl", timeout = 215}, "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12"],
  ["`", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", {tap = "backspace", hold = "lmet", timeout = 215}],
  ["tab", "q", "w", {tap = "f", hold = "lalt", timeout = 233}, "p", "b", "j", "l", "u", "y", ";", "[", "]", "\\"],
  ["caps", {tap = "a", hold = "qwerty", timeout = 250}, "r", {tap = "s", hold = "lctl", timeout = 233}, {tap = "t", hold = "lsft", timeout = 250}, {tap = "g", hold = "lmet", timeout = 233}, "m", {tap = "n", hold = "lsft", timeout = 250}, {tap = "e", hold = "lctl", timeout = 233}, {tap = "i", hold = "lalt", timeout = 233}, {tap = "o", hold = "qwerty", timeout = 215}, "'", {tap = "enter", hold = "rmet", timeout = 215}],
  [{tap = "(", hold = "lsft", timeout = 215}, "z", "x", "c", {tap = "d", hold = "lalt", timeout = 233}, {tap = "v", hold = "lmet", timeout = 233}, "k", {tap = "h", hold = "lmet", timeout = 233}, ",", ".", "/", {tap = ")", hold = "lsft", timeout = 215}],
  ["lctrl", "lalt", "lmeta", {tap = "space", hold = "qwerty", timeout = 250}, "ralt", "rmeta", "left", "down", "up", "right"]
]

[layer_keys]
qwerty = "caps"
kodamaq = "grv"
